### ISSUE TITLE
Redirect console output to log file

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#103]
Redirect (duplicae) console output to log file, so people can send complete console logs without taking screenshots of frozen/crashed game.

**Comment by Vadru93** [comment]
I guess should have an option to start loging since else the file might get pretty huge?

**Comment by DCxDemo** [comment]
command line keys? can you access those? like launch with -log key.

**Comment by Vadru93** [comment]
I think dll is loaded before so should be possible
