### ISSUE TITLE
loading level issue - controller briefly doesn't do anything

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#107]
When you load a level where all goals have been completed (see below image), pressing ollie doesn't do anything for a few seconds.

Issue was introduced in https://github.com/Vadru93/LevelMod/commit/1da31b48adc08197d8d47bcb193eba4fe91a9abf

![image](https://user-images.githubusercontent.com/2666951/109080601-bc956e80-76b5-11eb-824a-190ead6ad1bf.png)

**Comment by DCxDemo** [comment]
i don't think it's how we're supposed to fix it. it usually waits for X unheld, then starts the wait press loop. now as you reset the key state, if you hold ollie (X), it will insta skip all dialogs on end run.

**Comment by Vadru93** [comment]
I didn’t reset the whole keystate, only the timer part. But maybe instead of setting it to zero I should set it to time now since it seems if it’s zero game will handle it as unpressed.
