### ISSUE TITLE
Where are saves located? Settings and game saves

### ISSUE THREAD

**Issue by calebsw83** [Vadru93/LevelMod#139]
I'd like to sync my saves to the cloud, but I don't want to sync the entire game folder. It looks like /data/settings has some save/config files, but copying them over to a new machine didn't work out right for me. Anyone have any ideas? Thanks

**Comment by DCxDemo** [comment]
https://www.pcgamingwiki.com/wiki/Tony_Hawk's_Pro_Skater_3
![image](https://github.com/Vadru93/LevelMod/assets/13422696/fe68f51f-d904-4678-b002-773daaaaf734)
