### ISSUE TITLE
When i click "play thps3!" it says "file not found" and does not start

### ISSUE THREAD

**Issue by goodstuff626** [Vadru93/LevelMod#144]
After opening the launcher.exe and i click "play thps3" a dialog pops up that says "file not found" and does not start the game. How can I fix this problem? It opened and played good without the levelmod. I downloaded the 1.0.1 version from - http://www.thps-mods.com/forum/viewtopic.php?f=4&t=1085

 Using windows 10 64bit.

**Comment by DCxDemo** [comment]
don't use the launcher, just launch skate3.exe directly.
it's outdated and not shipped with the latest version of the mod.
you can run it as admin if you still want to use it.

**Comment by goodstuff626** [comment]
> don't use the launcher, just launch skate3.exe directly. it's outdated and not shipped with the latest version of the mod. you can run it as admin if you still want to use it.

Thank you for reply. Unfortunately when I try to launch skate3.exe I get the pop up "CD copy protection check failed", and it won't launch the game. 

(It makes no sense because before I installed the levelmod the regular game played perfectly fine. It is very frustrating why this is not working for me. I thought I followed directions exactly.)

**Comment by DCxDemo** [comment]
this is a known bug, disable msaa if you want to see videos. https://github.com/Vadru93/LevelMod/issues/78
it was mostly meant to be used as an online/freeskate mod, hence stuff like this always had really low priority.

**Comment by goodstuff626** [comment]
> this is a known bug, disable msaa if you want to see videos. #78 it was mostly meant to be used as an online/freeskate mod, hence stuff like this always had really low priority.

Ok. Thanks so much. 

But one last question, I notice when going to level select screen, for thps1, warehouse, burnside & roswell are greyed out/unselectable, also all levels from THUG are also greyed out/unselectable. I could have sworn they were all playable in this mod. Do I need to add a 100% save file to unlock them or...???
