### ISSUE TITLE
how to turn off vibration for xinput (with ds3 ds4 controller)

### ISSUE THREAD

**Issue by goodstuff626** [Vadru93/LevelMod#149]
I saw in the messages that on Mar 7, 2023 a vibration on or off was possibly added? (https://github.com/Vadru93/LevelMod/issues/114#issuecomment-1458572019) But I checked the .ini and ingame settings and could not find a way to turn off vibration. Is there a way to turn it off? (reason because the vibration is still to glitchy, vibrated when just ollieing not even grinding, in pause menu, and would rather just turn it off)

**Comment by Vadru93** [comment]
In levelmod settings menu there is a menu called Control Options, there you can toggle vibrations on/off. The setting in ini should be LM_Control_bVibration

**Comment by goodstuff626** [comment]
There is no LM_Control_bVibration setting in my ini file. And here is screenshot showing no vibration option in the control options. Also posting main menu screenshot showing I'm running levelmod 4.80. I already added the [2021-12-26] release. Is there a newer version I'm somehow missing?

![Screenshot (11)](https://github.com/Vadru93/LevelMod/assets/39889961/83b91825-49b4-4b85-90b3-62bda407bc56)
![Screenshot (12)](https://github.com/Vadru93/LevelMod/assets/39889961/74e44d46-5dea-4df1-87a7-ea2ea5520da9)

**Comment by Vadru93** [comment]
Yes, that's a very old version. You will have to download the files from the repo. It has been updated several times since 2021

**Comment by goodstuff626** [comment]
> Yes, that's a very old version. You will have to download the files from the repo. It has been updated several times since 2021

Ok, thanks for the help. But how do I download and add the files from the repo?
Is it the part on the main page that says "use the latest commit" that links to here?-https://github.com/Vadru93/LevelMod/tree/master/LevelMod
I don't see a way to download all the files at once, or do I have to right click and download each one separately, then add them to the correct folder and overwrite the old files?

**Comment by Vadru93** [comment]
If you don't want to download each file you need to download a git client for example from here https://desktop.github.com/

**Comment by DCxDemo** [comment]
code button -> download zip, it downloads entire repo at once

**Comment by goodstuff626** [comment]
> code button -> download zip, it downloads entire repo at once

Ok, I downloaded the entire repo zip and extracted it. I don't want to mess anything up, so how exactly should I add the folder. Do I just add the levelmod folder and overwrite everything? Or do I add everything from the zip folder as well? (res folder, source folder, .bat files)

**Comment by Vadru93** [comment]
You only need everything in the levelmod folder

**Comment by goodstuff626** [comment]
I added the files, and I was able to turn vibration to off in the settings, but it still vibrates with it set to off. I'm using ps4 controller. What could be the problem?
