### ISSUE TITLE
Add extra flatground tricks + dropdown

### ISSUE THREAD

**Issue by Vadru93** [Vadru93/LevelMod#15]
As the title says, add extra flatground tricks and drop down, as a base we can use levelout, 1.3 or 2.0 scripts.

**Comment by DCxDemo** [comment]
we're missing flatland pogo and one foot anims for a proper implementation.

**Comment by DCxDemo** [comment]
Addressed in https://github.com/Vadru93/LevelMod/commit/655a32adb5f6ed1316a0c09422e99f43da0386f7

**Comment by Vadru93** [comment]
Closing this since dropdown is added in ab442e9
