### ISSUE TITLE
Texture filtering

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#19]
Find a way to enable texture filtering for textures in TDX containers (mip maps).
Renderware supports mip maps natively. You can enable that by load textures separately in PNG format, mip maps are generated automatically, but that disables Neversoft material stuff as the default rendering is used.

**Comment by Vadru93** [comment]
I will look into this and when I get this and the shaders to work we should add a render option menu. I was thinking:
Shader Quality
Disabled
Normal(th4+ style)
High(extra effects like better environment)

Filtering
Disabled
2x
Etc

Water Effect
Disabled
Normal(some easy shader)
High(True reflective water)
