### ISSUE TITLE
Backwards manual

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#20]
Add backwards manual fix.

**Comment by Vadru93** [comment]
Should this be script fix like levelout, or memory fix like defmod?

**Comment by DCxDemo** [comment]
depends on what's bugged originally:
- if it's a problem like wrong function order or some missing function, it makes sense to fix it in qscript.
- if it's a bugged exe function, then probably dll fix is better.

**Comment by Vadru93** [comment]
I think defmod fixes it by just modifying a jump to from jne to je, or something similar.
Not sure how LevelOut fixed it thought, maybe he added some IF ENDIF, probably defmod is the more "tested official way"
