### ISSUE TITLE
Maybe the release should include more files?

### ISSUE THREAD

**Issue by Vadru93** [Vadru93/LevelMod#24]
I was thinking the release could include the font files, sound files, images etc. Everything except the levels.
Then when automatic update works it can check if level checksum changed and download levelpacks needed. For people who install for first time it will first check if new level folders exsists, if not download whole level pack.

**Comment by DCxDemo** [comment]
we probably should adopt xbox pre format at least for distribution.
then we can pack sounds and loadscreens to proper containers.
so tool downloads needed pre, unpacks to proper place and reloads the game, or does it in before actual game tries to access any content.

**Comment by Vadru93** [comment]
I already have code to zip and unzip, so I was thinking we could use zip files since I think zip is better compression?
For levelpacks we have 1 zip for each level folder and then in each level folder we have a file Containing the crc of the zip file and if the latest zip file has a different crc it will download that zip file.
