### ISSUE TITLE
Incorrect axis on ramp landing

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#3]
Occasionally when you land in ramp, skater is aligned to incorrect axis.
Once activated, it's only fixed by restart.

**Comment by Vadru93** [comment]
I think this mostly happens when you levelout without sucessfully spine transfer first

**Comment by Vadru93** [comment]
Fixed

**Comment by Vadru93** [comment]
I reopened this issue since it's not fixed in an optimal way.

**Comment by Vadru93** [comment]
This may be fixed in the beta testing branch.
Write here if you got this issue again.
