### ISSUE TITLE
Stable stuttering

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#35]
There is a noticable stuttering in the original game, happens 1-2 times every frame.
Some report it only happens in fullscreen mode, but that might be actually related to vsync on/off.
MSI Afterburner reports its running at stable 59fps, but frame length varies and there are noticable spike on the frametiem graph.
Possibly related to some sketchy main loop timer code.

Todo:
- research timer code, experiment with different d3d params, apply proper fixes

**Comment by Vadru93** [comment]
Is this solved now?

**Comment by DCxDemo** [comment]
It is.
