### ISSUE TITLE
Alt+Enter functionality - toggle windowed mode

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#50]
Let user swap between windowed/fullscreen mode on the fly by using widespread Alt+Enter combination.

**Comment by Vadru93** [comment]
As of now, for some reason it started to crash on alt tab again, will have to fix this first.

**Comment by Vadru93** [comment]
Added in  c598163
Current issues:
- [ ] Make it work when start game in windowed mode
- [ ] Make it so that game don't pause when alt tab in toggled windowed mode

**Comment by DCxDemo** [comment]
Alt pressed should probably block the usual enter functionality, cause you can enter menus now.

**Comment by Vadru93** [comment]
Ah right thats true

**Comment by DCxDemo** [comment]
Should check whether game started in windowed via command line key and change option accordingly. or ignore the key.
Also eventually crashes when swapping windowed and fullscreen multiple times in a row.

**Comment by Vadru93** [comment]
I kept the original windowed mode if someone prefer to use it instead of levelmod one(I use both myself). If you want to always start levelmod in new windowed, just enable it in options and launch without -windowed. I thought the crash was fixed awhile back, but maybe just made it crash less often.
