### ISSUE TITLE
Possible discord activity

### ISSUE THREAD

**Issue by WebbedMite11401** [Vadru93/LevelMod#58]
like if you were in canada on career it would show that as a subtitle with it showing a goal count for the level like 3 of 9 goals completed but that might be stretching it a little.

**Comment by Vadru93** [comment]
Is this even possible?

**Comment by DCxDemo** [comment]
with an api key i guess, but i'd guess it only works on desktop clients.
https://discord.com/developers/docs/game-sdk/activities

**Comment by Vadru93** [comment]
Sounds like quite some work and also needing to add extra files into the game for a not so important feature, so I'm closing this for now and if more people want this in the future or if everything else that's more important is already implemented it may be inplemented in the future.
