### ISSUE TITLE
Fix broken ollie sound position

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#68]
After a certain fix, ollie sound plays at a variable pan and volume.
Easy to spot performing multiple ollies in the row.
One jump you can hear normally, the other will be missing and another one will sound like it happened on the far right side.

**Comment by Vadru93** [comment]
This is not only related to ollie, can also sometimes hear the terrain sound lower or higher or even "lagging" and same with revert sound.
