### ISSUE TITLE
various issues

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#74]
Hi, I was just testing this out and noticed a few issues.  I believe some (or most) may already be known, however I wanted to report them just in case.

Could not find issues for the following:
- "File not found." when attempting to launch via launcher.exe
- right-clicking mouse crashes game when in menu
- accessing controller config sometimes crashes game
- attempting to open a movie crashes the game (affects credits as well)
- several options that should be enabled by default are not (E.g. 251x Patch, Unlimited Tags, Net Sky(?))

Problems I encountered that may be related to existing issues:
- xinput only partially works https://github.com/Vadru93/LevelMod/issues/6
- missing shadow https://github.com/Vadru93/LevelMod/issues/49
- large black square in the top left hand corner https://github.com/Vadru93/LevelMod/issues/49
- unable to change buffering / msaa level via UI (results in an error box popping up)
- buffering / msaa level not aligned in menu

**Comment by DCxDemo** [comment]
* "File not found." when attempting to launch via launcher.exe
Launch as admin. Launcher is deprecated and not a part of current levelmod iteration.
* right-clicking mouse crashes game when in menu
Bug confirmed.
* accessing controller config sometimes crashes game
Could be some random bug in menu or XInput code.
* attempting to open a movie crashes the game (affects credits as well)
Bug confirmed.
* several options that should be enabled by default are not (E.g. 251x Patch, Unlimited Tags, Net Sky(?))
Open to discussion. I guess i's aimed to keep vanilla game settings by default.

* unable to change buffering / msaa level via UI (results in an error box popping up)
* buffering / msaa level not aligned in menu
Graphics menu is not finished yet.

**Comment by buvk** [comment]
> * several options that should be enabled by default are not (E.g. 251x Patch, Unlimited Tags, Net Sky(?))
>   Open to discussion. I guess i's aimed to keep vanilla game settings by default.

Understood.  I only mentioned this because the wiki indicated that these were supposed to have been on by default.

With regards to Net Sky, by default skies had low detail.  In order to restore (default?) vanilla behavior, Net Sky has to be turned on.

Thanks!

**Comment by Vadru93** [comment]
The wiki is far from finished, as for 251x patch it's a mistake in the wiki. However for the unlimited tags, it should be enabled by default, if you check settings.q it says "bLimitTags Value = 0".
This setting is kinda missleading in code since it's actually called bLimitTags, so setting it to true will LIMIT tags not UNLIMIT them.
