### ISSUE TITLE
Right-clicking mouse crashes game when in menu

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#75]
Right-clicking mouse crashes game when in menu as reported in #74

**Comment by Vadru93** [comment]
I have some vague memory that we had some similar issue before. I guess traceback to when this started to happen is needed.

**Comment by DCxDemo** [comment]
here's the commit that introduced the bug
crash	18 Nov 2020	Some optimizations to the game code
works	5 Nov 2020	Fixed Air and Wall menu + added NS eye in loadingscreen

**Comment by Vadru93** [comment]
Thanks for the help. For future you can actually link the commit by typing the md5, for example ”18 Nov 6945e7e7f3e04ae8631ed00d8a51718d8a20fd12” will produce 18 Nov 6945e7e7f3e04ae8631ed00d8a51718d8a20fd12
