### ISSUE TITLE
Controller stops being recognized after comp

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#84]
This can be reproduced in career mode.  Go to Rio, finish all 3 rounds of comp.  Controller will no longer work.

**Comment by Vadru93** [comment]
Was this here in older versions of levelmod?

**Comment by buvk** [comment]
It looks like you can't even play comps properly in levelmod 4.1.  Rio is treated like a regular level (2 min run).

**Comment by buvk** [comment]
I have attempted numerous times to replicate this today using the same version I was having issues with the other day.  Out of roughly 30 attempts, I have only been able to replicate this once.  This is going to be tough to narrow down.

**Comment by Vadru93** [comment]
If we fix the other bugs I think this bug will get fixed aswell

**Comment by Vadru93** [comment]
This is not only controller, it happened to me aswell on keyboard and is probably related to #80 so we really need to try to figure out when those 2 bugs started to happen. But since they are pretty rare it’s not easy.

**Comment by buvk** [comment]
I suspect the issue may have been introduced in this commit https://github.com/Vadru93/LevelMod/commit/5f540f364474acca05ee3064c02781465a121a8b

I have been able to replicate it 3 times in a row.

I have not been able to replicate it so far on the previous commit.

**Comment by Vadru93** [comment]
It must be earlier, that commit didn’t change anything.

**Comment by buvk** [comment]
You are right.  I was able to replicate it in the previous commit.  Just took longer.

**Comment by buvk** [comment]
I've been able to replicate this as far back as https://github.com/Vadru93/LevelMod/commit/c598163ea216818a1d88fc7e0b52ef2b593f2db2

I have been testing the previous commit https://github.com/Vadru93/LevelMod/commit/f89cf0d1fa288ea0de6eb3edc9b73b5437fb5637 for a while, and still have not been able to replicate it yet.

**Comment by Vadru93** [comment]
I’m pretty sure it’s further back. But I have an idea what it could be now. If I can’t fix it with that idea it for sure is earlier.

**Comment by Vadru93** [comment]
I’m now sure it has to be earlier.

**Comment by Vadru93** [comment]
I think this is fixed now?

**Comment by buvk** [comment]
@Vadru93 unfortunately I can still replicate this issue.

One thing I just noticed is that the controller/buttons start being recognized again after around 60 seconds.

**Comment by Vadru93** [comment]
Did you test this with latest commit?

**Comment by buvk** [comment]
> Did you test this with latest commit?

Yep
