### ISSUE TITLE
Judges glitched out at end of Rio comp

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#85]
See image below :)

![image](https://user-images.githubusercontent.com/2666951/106084163-aacea480-60d2-11eb-9159-fe0c54496875.png)

**Comment by Vadru93** [comment]
Could you check in which commit this started to happen?

**Comment by buvk** [comment]
Started here https://github.com/Vadru93/LevelMod/commit/ea09634ff569647e64aefbc556f35eb84d384597
You need to finish the second round before they start to glitch out

**Comment by Vadru93** [comment]
fixed in 0bc038b1abd6db38825d893dd8f1cac1a91b2017
