### ISSUE TITLE
Longer load times when (re)starting a level

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#88]
In vanilla THPS3, starting or re-starting a level is almost instant.  In LevelMod, there is roughly a 1 to 2 second pause.

**Comment by DCxDemo** [comment]
it's a trade-off for the new features. at the very least it generates mip maps for all textures now and it can't be instant. i wouldn't consider that a bug, but rather a low priority optimization request.

**Comment by Vadru93** [comment]
Does disable filtering reduce loading times?

**Comment by buvk** [comment]
Doesn't appear to make a difference.

**Comment by Vadru93** [comment]
Do you have the same issue in this commit https://github.com/Vadru93/LevelMod/commit/2beb1ee1b3d580980eca7cd25d1fb37f9ba57444

**Comment by buvk** [comment]
The issue occurs in that commit as well

**Comment by Vadru93** [comment]
Btw it seems that you need to restart game after disabling filtering to really disable it

**Comment by buvk** [comment]
> Btw it seems that you need to restart game after disabling filtering to really disable it

Yep, I made sure to do this.

**Comment by Vadru93** [comment]
Well then I really don't know what can be the cause of it. And probably it cannot be optimized to be much faster than it already is.

**Comment by buvk** [comment]
The issue started on this commit https://github.com/Vadru93/LevelMod/commit/30112355884c9252d735ef09856c2d0d40bb953a

**Comment by Vadru93** [comment]
So I already know what it is. It’s some debug info code that I will move to debug version of levelmod. Thanks for the find!
