### ISSUE TITLE
Sound effects don't always play - vanilla bug

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#89]
In vanilla and in LevelMod, there is an issue where sounds effects sometimes are not played (E.g. revert doesn't make any sound at all).

**Comment by buvk** [comment]
https://user-images.githubusercontent.com/2666951/106215604-2d646c00-6186-11eb-9b25-a971d5e485fb.mp4

**Comment by DCxDemo** [comment]
are you testing the latest commit? revert sound bug was caused by volume being tied to skater speed and it was fixed a while ago. if there is some specific place where it happens, it's probably not a code bug, but original level bug like polygon is not tagged as valid material.

**Comment by buvk** [comment]
I tested the latest commit.  I attached a video for reference if that helps (I think you have to download it in order to see it).  As noted earlier, this does occur in vanilla THPS3 as well.  It is not just a LevelMod issue.

**Comment by DCxDemo** [comment]
it's exactly that. the graffiti is mistakenly collidable and has no sound attached. for example you can also notice that you can skate on water in warehouse. these are not code bugs, but content bugs. it would require to edit bsp file, which is unlikely to happen, or add some memory patches to track specific objects and apply changes on the fly. it's too much work for a too minor and specific thing and i'd imagine it would be hard to support, but it's up to vadru if he wants to implement that.

**Comment by Vadru93** [comment]
I guess could play some default soumd instead of no sound, since no sound should never happen?

**Comment by buvk** [comment]
Awesome, thank you!
