### ISSUE TITLE
Loading Suburbia in career mode crashes the game

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#90]
Issue started after this commit https://github.com/Vadru93/LevelMod/commit/8451d4a195674d75580c9f8e26acdf2f641d10ee

**Comment by buvk** [comment]
Issues started after this commit https://github.com/Vadru93/LevelMod/commit/8451d4a195674d75580c9f8e26acdf2f641d10ee

**Comment by Vadru93** [comment]
I couldn't reproduce this in latest commit

**Comment by buvk** [comment]
Confirmed this does not occur in the latest commit.

Thanks!
