### ISSUE TITLE
Shattered glass wrong color in LA

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#96]
Shattered glass in LA is the wrong color, but only when you are facing away from the fountain.  Does not happen in vanilla.

LevelMod
![image](https://user-images.githubusercontent.com/2666951/106390030-3b3f0a80-639b-11eb-907d-875e5cd80332.png)

Console
![image](https://user-images.githubusercontent.com/2666951/106389479-565c4b00-6398-11eb-8147-7316c63a6b1d.png)

**Comment by Vadru93** [comment]
This is a known issue with the new shatter rendering and does not only happen in LA.

**Comment by DCxDemo** [comment]
it's also rendered 1 sided, is there any reason for that?

**Comment by Vadru93** [comment]
https://github.com/Vadru93/LevelMod/blob/852079f6f6c61bcb599e494804c01714ae1ddbce/source/Physics/Shatter.cpp#L409
It should be 2 sided since no culling is applied

**Comment by DCxDemo** [comment]
here's the moment it shatters, you can see 1 triangle is faced forward, the other one is faced backwards. you can eventually see some bits from the other triangle as they rotate.

![Skate3_2021_02_10_11_26_52_499](https://user-images.githubusercontent.com/13422696/107490696-e8333780-6b92-11eb-8c48-cbd4da0a5b1d.jpg)

**Comment by Vadru93** [comment]
https://github.com/Vadru93/LevelMod/blob/852079f6f6c61bcb599e494804c01714ae1ddbce/source/Objects/Mesh.h#L235
I found the problem, I need to look into how matetiald are submited. Probably uncommenting the Submit_Original will fix this issue.

**Comment by DCxDemo** [comment]
that fixed it. what about the color inversion? i think it's original material rendering bug. did you try other material flags?
