### ISSUE TITLE
Extra levels listed in career when changing levels

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#98]
Extra levels are listed in career mode when changing levels.  Also noticed that vanilla has extra space underneath cruise ship for some reason.

LevelMod:
![image](https://user-images.githubusercontent.com/2666951/106546822-e1d0fb80-64c0-11eb-9204-6f349b02352a.png)

Vanilla PC
![image](https://user-images.githubusercontent.com/2666951/106547335-e4802080-64c1-11eb-8937-af8587706034.png)

Console
![image](https://user-images.githubusercontent.com/2666951/106547123-750a3100-64c1-11eb-813c-a51097b63cef.png)

**Comment by DCxDemo** [comment]
It happens because you don't physically have level files and the code to make element static was applied before career level check.
