### ISSUE TITLE
Add option to invert secondary analog (camera) X-axis

### ISSUE THREAD

**Issue by buvk** [Vadru93/LevelMod#99]
Would this be possible? It doesn't seem possible to do via THPS3Setup.

**Comment by Vadru93** [comment]
Sure is possible, are you using th3 supported controller or xinput?

**Comment by buvk** [comment]
Xinput controller which I can use with thps3 either by using vjoy (ugh), or
using a hardware adapter that translates xinput to directinput.

**Comment by Vadru93** [comment]
Did you test levelmods xinput?
I don’t have a controller so I can’t test it, some say it work and some say not

**Comment by DCxDemo** [comment]
how some may say it works if sThumbRX/sThumbRY  is not even processed in KeyState.cpp :P

**Comment by Vadru93** [comment]
Oh well didn’t know this key was not in there. But some say the keys that are in there works. But I never got anything to work with that emulation software.

**Comment by buvk** [comment]
> Did you test levelmods xinput?
> I don’t have a controller so I can’t test it, some say it work and some say not

If I enable it, left analog works in menu.  None of the buttons do anything.  In level, nothing works.

**Comment by DCxDemo** [comment]
well let's discuss xinput problems in #6
